[profile.default]
  auto_detect_solc = false
  bytecode_hash = "none"
  cbor_metadata = false
  libs = ["lib"]
  optimizer = true
  optimizer_runs = 10_000
  out = "out"
  solc = "0.8.19"
  src = "src"
  test = "test"

  # See more config options https://github.com/foundry-rs/foundry/tree/master/config
